[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Tang <out_tang_look@outlook.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
rustc-serialize = "0.3.24"
rayon = "0.4"
